// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until} = require('selenium-webdriver');
const chai = require('chai');
const expect = chai.expect;
const chrome = require('selenium-webdriver/chrome');

const screen = {
  width: 1080,
  height: 1920
};


describe('Harvest a planted onion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    let chrome_options = new chrome.Options().headless().windowSize(screen);
    //let chrome_options = new chrome.Options().windowSize(screen);

    driver = await new Builder()
            .forBrowser('chrome')
            .setChromeOptions(chrome_options)
            .build();

    // 1 | open | http://127.0.0.1:5501/bahay_cube.html | 
    await driver.get("http://127.0.0.1:5501/bahay_cube.html")
    // 2 | setWindowSize | 1294x1392 | 
    await driver.manage().window().setRect({ width: 1294, height: 1392 })
    // 3 | click | id=tile_id_5 | 
    await driver.findElement(By.id("tile_id_5")).click()
    // 4 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 5 | click | id=tile_id_5 | 
    await driver.findElement(By.id("tile_id_5")).click()
    // 6 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it("Selected tile class should have 'onion_planted'", async function() {
    // 7 | click | xpath=//label[@id='onion_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'onion_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | verifyElementPresent | css=.onion_planted | 
    selected_tile  = await driver.findElement(By.id("tile_id_5"));
    let tile_class = await selected_tile.getAttribute('class');
    expect(tile_class.split(" ")[1]).to.eq('onion_planted');
  })

  it("Total Earnings should have a value of 85 after planting onion crop", async function() {
    // 7 | click | xpath=//label[@id='onion_crop'] | \
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'onion_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | verifyText | css=.total_earnings_value | 85
    let total_earnings = await driver.findElement(By.css(".total_earnings_value")).getText()
    expect(total_earnings).to.eq("85");
  })

  it("Planted onion tile should have 8 seconds waiting time to harvest", async function() {
    // 7 | click | xpath=//label[@id='potato_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'potato_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | waitForElementPresent | css=.harvest | 5000
    await driver.wait(until.elementLocated(By.css(".harvest")), 8000)
    selected_tile  = await driver.findElement(By.id("tile_id_5"));
    let tile_class = await selected_tile.getAttribute('class');
    expect(tile_class.split(" ")[1]).to.eq('harvest');
  })

  it("Planted onion tile should have $25 tile text", async function() {
    // 7 | click | xpath=//label[@id='onion_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'onion_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | waitForElementPresent | css=.harvest | 8000
    await driver.wait(until.elementLocated(By.css(".harvest")), 8000)
    // 10 | waitForText | css=#tile_id_5 > .tile_text | $15
    selected_tile = await driver.wait(until.elementTextIs(await driver.findElement(By.css("#tile_id_5 > .tile_text")), '$25'), 8200)
    let tile_text = await selected_tile.getText();
    expect(tile_text).to.eq('$25');
  })

  it("Total earnings should be $110 after harvesting onion crop", async function() {
    // 7 | click | xpath=//label[@id='onion_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'onion_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | waitForElementPresent | css=.harvest | 8000
    await driver.wait(until.elementLocated(By.css(".harvest")), 8000)
    // 10 | waitForText | css=#tile_id_5 > .tile_text | $25
    await driver.wait(until.elementTextIs(await driver.findElement(By.css("#tile_id_5 > .tile_text")), '$25'), 8700)
    // 11 | click | id=tile_id_5 | 
    await driver.findElement(By.id("tile_id_5")).click()
    // 12 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 13 | verifyText | css=.total_earnings_value | 110
    let total_earnings = await driver.findElement(By.css(".total_earnings_value")).getText()
    expect(total_earnings).to.eq("110");
  })
})
