// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until} = require('selenium-webdriver');
const chai = require('chai');
const expect = chai.expect;
const chrome = require('selenium-webdriver/chrome');

const screen = {
  width: 1080,
  height: 1920
};

describe('Harvest a planted corn', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    let chrome_options = new chrome.Options().headless().windowSize(screen);
    //let chrome_options = new chrome.Options().windowSize(screen);

    driver = await new Builder()
            .forBrowser('chrome')
            .setChromeOptions(chrome_options)
            .build();

    // 1 | open | http://127.0.0.1:5501/bahay_cube.html | 
    await driver.get("http://127.0.0.1:5501/bahay_cube.html")
    // 2 | setWindowSize | 1294x1392 | 
    await driver.manage().window().setRect({ width: 1294, height: 1392 })
    // 3 | click | id=tile_id_15 | 
    await driver.findElement(By.id("tile_id_15")).click()
    // 4 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 5 | click | id=tile_id_15 | 
    await driver.findElement(By.id("tile_id_15")).click()
    // 6 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  it("Selected tile class should have 'corn_planted'", async function() {
    // 7 | click | xpath=//label[@id='corn_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'corn_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | verifyElementPresent | css=.corn_planted | 
    selected_tile  = await driver.findElement(By.id("tile_id_15"));
    let tile_class = await selected_tile.getAttribute('class');
    expect(tile_class.split(" ")[1]).to.eq('corn_planted');
  })

  it("Total Earnings should have a value of 65 after planting corn crop", async function() {
    // 7 | click | xpath=//label[@id='corn_crop'] | \
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'corn_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 10 | verifyText | css=.total_earnings_value | 65
    let total_earnings = await driver.findElement(By.css(".total_earnings_value")).getText()
    expect(total_earnings).to.eq("65");
  })

  it("Planted corn tile should have 12 seconds waiting time to harvest", async function() {
    // 7 | click | xpath=//label[@id='corn_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'corn_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | waitForElementPresent | css=.harvest | 12000
    await driver.wait(until.elementLocated(By.css(".harvest")), 12200)
    selected_tile  = await driver.findElement(By.id("tile_id_15"));
    let tile_class = await selected_tile.getAttribute('class');
    expect(tile_class.split(" ")[1]).to.eq('harvest');
  })

  it("Planted corn tile should have $100 tile text", async function() {
    // 7 | click | xpath=//label[@id='corn_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'corn_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | waitForElementPresent | css=.harvest | 12000
    await driver.wait(until.elementLocated(By.css(".harvest")), 12200)
    // 10 | waitForText | css=#tile_id_5 > .tile_text | $100
    selected_tile = await driver.wait(until.elementTextIs(await driver.findElement(By.css("#tile_id_15 > .tile_text")), '$100'), 12200)
    let tile_text = await selected_tile.getText();
    expect(tile_text).to.eq('$100');
  })

  it("Total earnings should be $165 after harvesting corn crop", async function() {
    // 7 | click | xpath=//label[@id='corn_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'corn_crop\']"))), 1000).click()
    await driver.sleep(1000);
    // 8 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 9 | waitForElementPresent | css=.harvest | 12000
    await driver.wait(until.elementLocated(By.css(".harvest")), 12200)
    // 10 | waitForText | css=#tile_id_15 > .tile_text | $100
    await driver.wait(until.elementTextIs(await driver.findElement(By.css("#tile_id_15 > .tile_text")), '$100'), 12200)
    // 11 | click | id=tile_id_15 | 
    await driver.findElement(By.id("tile_id_15")).click()
    // 12 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 13 | verifyText | css=.total_earnings_value | 165
    let total_earnings = await driver.findElement(By.css(".total_earnings_value")).getText()
    expect(total_earnings).to.eq("165");
  })
})
