// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until} = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome');

const screen = {
  width: 1920,
  height: 1080
};

describe('harvest_carrot_crop', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    let chrome_options = new chrome.Options().headless().windowSize(screen);
    //let chrome_options = new chrome.Options().windowSize(screen);

    driver = await new Builder()
            .forBrowser('chrome')
            .setChromeOptions(chrome_options)
            .build();
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('harvest_carrot_crop', async function() {
    // Test name: harvest_carrot_crop
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5501/bahay_cube.html | 
    await driver.get("http://127.0.0.1:5501/bahay_cube.html")
    // 2 | setWindowSize | 1294x1392 | 
    await driver.manage().window().setRect({ width: 1294, height: 1392 })
    // 3 | click | id=tile_id_10 | 
    await driver.findElement(By.id("tile_id_10")).click()
    // 4 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 5 | click | id=tile_id_10 | 
    await driver.findElement(By.id("tile_id_10")).click()
    // 6 | verifyElementPresent | css=.tilled | 
    {
      const elements = await driver.findElements(By.css(".tilled"))
      assert(elements.length)
    }
    // 7 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    // 8 | click | xpath=//label[@id='carrot_crop'] | 
    await driver.wait(until.elementIsVisible(await driver.findElement(By.xpath("//label[@id=\'carrot_crop\']"))), 3000)
    await driver.findElement(By.xpath("//label[@id=\'carrot_crop\']")).click()
    await driver.sleep(2000);
    // 9 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 10 | verifyElementPresent | css=.carrot_planted | 
    {
      const elements = await driver.findElements(By.css(".carrot_planted"))
      assert(elements.length)
    }
    // 11 | verifyText | css=.total_earnings_value | 75
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "75")
    // 12 | waitForElementPresent | css=.harvest | 10000
    await driver.wait(until.elementLocated(By.css(".harvest")), 10200)
    // 13 | waitForText | css=#tile_id_10 > .tile_text | $75
    await driver.wait(until.elementTextIs(await driver.findElement(By.css("#tile_id_10 > .tile_text")), '$75'), 30000)
    // 14 | click | id=tile_id_10 | 
    await driver.findElement(By.id("tile_id_10")).click()
    // 15 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 16 | verifyText | css=.total_earnings_value | 150
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "150")
  })
})
