// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('tilled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('tilled', async function() {
    // Test name: tilled
    // Step # | name | target | value
    // 1 | open | http://127.0.0.1:5501/bahay_cube.html | 
    await driver.get("http://127.0.0.1:5501/bahay_cube.html")
    // 2 | setWindowSize | 1294x1392 | 
    await driver.manage().window().setRect({ width: 1294, height: 1392 })
    // 3 | click | id=tile_id_0 | 
    await driver.findElement(By.id("tile_id_0")).click()
    // 4 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 5 | click | id=tile_id_5 | 
    await driver.findElement(By.id("tile_id_5")).click()
    // 6 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 7 | click | id=tile_id_10 | 
    await driver.findElement(By.id("tile_id_10")).click()
    // 8 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 9 | click | id=tile_id_15 | 
    await driver.findElement(By.id("tile_id_15")).click()
    // 10 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 11 | click | id=tile_id_0 | 
    await driver.findElement(By.id("tile_id_0")).click()
    // 12 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    // 13 | click | xpath=//label[@id='potato_crop'] | 
    await driver.findElement(By.xpath("//label[@id=\'potato_crop\']")).click()
    // 14 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 15 | click | id=tile_id_5 | 
    await driver.findElement(By.id("tile_id_5")).click()
    // 16 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    // 17 | click | css=#onion_crop > .tile_text | 
    await driver.findElement(By.css("#onion_crop > .tile_text")).click()
    // 18 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 19 | click | id=tile_id_10 | 
    await driver.findElement(By.id("tile_id_10")).click()
    // 20 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    // 21 | click | xpath=//label[@id='carrot_crop'] | 
    await driver.findElement(By.xpath("//label[@id=\'carrot_crop\']")).click()
    // 22 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 23 | click | id=tile_id_15 | 
    await driver.findElement(By.id("tile_id_15")).click()
    // 24 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    // 25 | click | xpath=//label[@id='corn_crop'] | 
    await driver.findElement(By.xpath("//label[@id=\'corn_crop\']")).click()
    // 26 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 27 | assertText | css=.total_earnings_value | 15
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "15")
    // 28 | waitForElementPresent | css=.harvest | 30000
    await driver.wait(until.elementLocated(By.css(".harvest")), 30000)
    // 29 | click | id=tile_id_0 | 
    await driver.findElement(By.id("tile_id_0")).click()
    // 30 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 31 | verifyText | css=.total_earnings_value | 30
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "30")
    // 32 | waitForElementPresent | css=.harvest | 30000
    await driver.wait(until.elementLocated(By.css(".harvest")), 30000)
    // 33 | click | id=tile_id_5 | 
    await driver.findElement(By.id("tile_id_5")).click()
    // 34 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 35 | verifyText | css=.total_earnings_value | 55
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "55")
    // 36 | waitForElementPresent | css=.harvest | 30000
    await driver.wait(until.elementLocated(By.css(".harvest")), 30000)
    // 37 | click | id=tile_id_10 | 
    await driver.findElement(By.id("tile_id_10")).click()
    // 38 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 39 | verifyText | css=.total_earnings_value | 130
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "130")
    // 40 | waitForElementPresent | css=.harvest | 30000
    await driver.wait(until.elementLocated(By.css(".harvest")), 30000)
    // 41 | click | id=tile_id_15 | 
    await driver.findElement(By.id("tile_id_15")).click()
    // 42 | click | id=harvest_btn | 
    await driver.findElement(By.id("harvest_btn")).click()
    // 43 | verifyText | css=.total_earnings_value | 230
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "230")
    // 44 | click | id=tile_id_1 | 
    await driver.findElement(By.id("tile_id_1")).click()
    // 45 | click | css=.till_btn | 
    await driver.findElement(By.css(".till_btn")).click()
    // 46 | click | id=tile_id_1 | 
    await driver.findElement(By.id("tile_id_1")).click()
    // 47 | click | css=.plant_btn | 
    await driver.findElement(By.css(".plant_btn")).click()
    // 48 | click | xpath=//label[@id='potato_crop'] | 
    await driver.findElement(By.xpath("//label[@id=\'potato_crop\']")).click()
    // 49 | click | id=crop_to_plant_btn | 
    await driver.findElement(By.id("crop_to_plant_btn")).click()
    // 50 | verifyText | css=.total_earnings_value | 220
    assert(await driver.findElement(By.css(".total_earnings_value")).getText() == "220")
    // 51 | click | id=tile_id_1 | 
    await driver.findElement(By.id("tile_id_1")).click()
    // 52 | click | css=.remove_btn | 
    await driver.findElement(By.css(".remove_btn")).click()
    // 53 | click | css=.remove_modal_remove_btn | 
    await driver.findElement(By.css(".remove_modal_remove_btn")).click()
  })
})
